//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rahmatullah_1250255.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookId { get; set; }
        public int PublisherId { get; set; }
        public string BookName { get; set; }
        public decimal BookPrice { get; set; }
        public string CoverPage { get; set; }
    
        public virtual Publisher Publisher { get; set; }
    }
}
